name: Tips
favicon: null
layout_spectrum: 0.12858403637073934
typography_spectrum: 0.47059342497959733
title: "Stuff I've been taught."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9634589655324817
  lightness: 0.3480700326617807
  saturation: 0.5195454568602145
  rhythmicContrast: 0.49158405675552785
purpose: []
